-- =============================================================================
-- JOB MARKET INTELLIGENCE & SKILL ANALYTICS PLATFORM
-- -----------------------------------------------------------------------------
-- File      : schema.sql
-- Database  : PostgreSQL 14+
-- Stage     : Database Design  (schema only - NO data is inserted here)
-- Owner     : AIML student portfolio project
--
-- WHAT THIS FILE CREATES
--   1. companies  - employer dimension (one company, many jobs)
--   2. jobs       - job posting fact (one job, belongs to one company)
--   3. skills     - skill dimension (one skill, required by many jobs)
--   4. job_skills - junction table resolving the jobs <-> skills MANY-TO-MANY
--
-- CONVENTIONS USED THROUGHOUT
--   * Table names   : lowercase, singular, snake_case        (e.g. job_skills)
--   * Column names  : lowercase snake_case                    (e.g. salary_min)
--   * Primary key   : <table>_id                            (e.g. job_id)
--   * Foreign key   : <referenced_table>_id                 (e.g. company_id)
--   * Timestamps    : <event>_at, stored as TIMESTAMPTZ (UTC)
--   * Enumerations  : UPPER_SNAKE_CASE text + CHECK constraint (portable, and
--                     easy to extend without ALTER TYPE locks)
--   * Money         : NUMERIC(12,2) - never floating point for currency
--   * Identifiers   : GENERATED BY DEFAULT AS IDENTITY (PostgreSQL 10+)
--   * Every FK has an explicit ON DELETE action, so referential integrity
--     behaviour is declared, never accidental.
--
-- HOW TO APPLY
--   psql -U <user> -d <database> -f database/schema.sql
--
-- NOTE
--   The DROP statements at the top exist so this file can be re-run during
--   development. Remove them before using this file anywhere real.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 0. DEVELOPMENT-ONLY RESET  (reverse dependency order: children before parents)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS job_skills;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS companies;


-- =============================================================================
-- 1. companies
--    The employer dimension. One row per real-world company.
--    -> 1 company : MANY jobs   (enforced by jobs.company_id)
-- =============================================================================
CREATE TABLE companies (
    company_id      INTEGER             GENERATED BY DEFAULT AS IDENTITY,
    company_name    TEXT                NOT NULL,
    industry        TEXT                NOT NULL,
    company_size    TEXT,
    headquarters    TEXT,
    created_at      TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ         NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_companies
        PRIMARY KEY (company_id),

    -- One row per company: the same employer must not be stored twice.
    CONSTRAINT uq_companies_company_name
        UNIQUE (company_name),

    -- Non-empty text checks (a blank string is not real data).
    CONSTRAINT chk_companies_company_name_not_blank
        CHECK (btrim(company_name) <> ''),

    CONSTRAINT chk_companies_industry_not_blank
        CHECK (btrim(industry) <> ''),

    -- Normalised headcount buckets. NULL = size not disclosed.
    CONSTRAINT chk_companies_company_size_valid
        CHECK (company_size IS NULL OR company_size IN
            ('MICRO_1_10', 'SMALL_11_50', 'MEDIUM_51_200', 'LARGE_201_500',
             'XLARGE_501_1000', 'ENTERPRISE_1000_PLUS', 'UNKNOWN')),

    CONSTRAINT chk_companies_headquarters_not_blank
        CHECK (headquarters IS NULL OR btrim(headquarters) <> '')
);


-- =============================================================================
-- 2. jobs
--    The fact table: one row per job posting.
--    -> MANY jobs : 1 company  (jobs.company_id -> companies.company_id)
--    -> 1 job     : MANY skills (resolved through job_skills)
-- =============================================================================
CREATE TABLE jobs (
    job_id           INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    company_id       INTEGER         NOT NULL,
    job_title        TEXT            NOT NULL,
    location         TEXT            NOT NULL,
    country          TEXT            NOT NULL,
    employment_type  TEXT            NOT NULL,
    work_mode        TEXT            NOT NULL,
    experience_min   SMALLINT,
    experience_max   SMALLINT,
    salary_min       NUMERIC(12, 2),
    salary_max       NUMERIC(12, 2),
    -- TEXT, not CHAR(3): CHAR blank-pads 'IN' to 'IN ', which breaks the
    -- ISO-4217 format check below.
    currency         TEXT,
    salary_period    TEXT,
    posted_date      DATE            NOT NULL,
    description      TEXT,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_jobs
        PRIMARY KEY (job_id),

    -- If a company is deleted, its postings go with it (a posting is meaningless
    -- without its employer). CASCADE is declared explicitly, not by accident.
    CONSTRAINT fk_jobs_company
        FOREIGN KEY (company_id)
        REFERENCES companies (company_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_jobs_job_title_not_blank
        CHECK (btrim(job_title) <> ''),

    CONSTRAINT chk_jobs_location_not_blank
        CHECK (btrim(location) <> ''),

    CONSTRAINT chk_jobs_country_not_blank
        CHECK (btrim(country) <> ''),

    -- Controlled vocabularies. 'UNKNOWN'/'OTHER' exist so that missing source
    -- data is recorded honestly instead of being guessed.
    CONSTRAINT chk_jobs_employment_type_valid
        CHECK (employment_type IN
            ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP',
             'TEMPORARY', 'FREELANCE', 'OTHER', 'UNKNOWN')),

    CONSTRAINT chk_jobs_work_mode_valid
        CHECK (work_mode IN ('REMOTE', 'HYBRID', 'ONSITE', 'UNKNOWN')),

    -- Experience: non-negative and logically ordered (min <= max).
    CONSTRAINT chk_jobs_experience_min_valid
        CHECK (experience_min IS NULL OR experience_min >= 0),

    CONSTRAINT chk_jobs_experience_max_valid
        CHECK (experience_max IS NULL OR experience_max >= 0),

    CONSTRAINT chk_jobs_experience_range
        CHECK (experience_max IS NULL OR experience_min IS NULL
               OR experience_max >= experience_min),

    -- Salary: non-negative and logically ordered (min <= max).
    CONSTRAINT chk_jobs_salary_min_valid
        CHECK (salary_min IS NULL OR salary_min >= 0),

    CONSTRAINT chk_jobs_salary_max_valid
        CHECK (salary_max IS NULL OR salary_max >= 0),

    CONSTRAINT chk_jobs_salary_range
        CHECK (salary_max IS NULL OR salary_min IS NULL
               OR salary_max >= salary_min),

    -- If any salary figure exists, a currency and a period must exist too,
    -- otherwise the number is meaningless.
    CONSTRAINT chk_jobs_salary_requires_currency
        CHECK ((salary_min IS NULL AND salary_max IS NULL) OR currency IS NOT NULL),

    CONSTRAINT chk_jobs_salary_requires_period
        CHECK ((salary_min IS NULL AND salary_max IS NULL) OR salary_period IS NOT NULL),

    CONSTRAINT chk_jobs_currency_iso4217
        CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$'),

    CONSTRAINT chk_jobs_salary_period_valid
        CHECK (salary_period IS NULL OR salary_period IN
            ('YEARLY', 'MONTHLY', 'HOURLY', 'DAILY', 'WEEKLY'))

);


-- =============================================================================
-- 3. skills
--    The skill dimension. One row per distinct, normalised skill name.
--    -> MANY skills : MANY jobs (resolved through job_skills)
-- =============================================================================
CREATE TABLE skills (
    skill_id         INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    skill_name       TEXT            NOT NULL,
    skill_category   TEXT            NOT NULL,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_skills
        PRIMARY KEY (skill_id),

    CONSTRAINT chk_skills_skill_name_not_blank
        CHECK (btrim(skill_name) <> ''),

    CONSTRAINT chk_skills_category_not_blank
        CHECK (btrim(skill_category) <> '')
);


-- Case-insensitive uniqueness is enforced here (and only here): real job data
-- contains "Python", "python" and "PYTHON", which would otherwise be counted
-- as three different skills and corrupt every skill ranking.
CREATE UNIQUE INDEX uq_skills_skill_name_lower
    ON skills (lower(btrim(skill_name)));


-- =============================================================================
-- 4. job_skills  (junction / associative table)
--    Resolves the MANY-TO-MANY relationship between jobs and skills.
--    One row = "this job requires this skill".
--    - Composite PRIMARY KEY (job_id, skill_id) prevents duplicate combinations.
--    - No surrogate id column: the pair IS the identity, which is the simplest
--      correct design and keeps the table small.
-- =============================================================================
CREATE TABLE job_skills (
    job_id           INTEGER         NOT NULL,
    skill_id         INTEGER         NOT NULL,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_job_skills
        PRIMARY KEY (job_id, skill_id),

    -- Deleting a job removes its skill links (they are useless without the job).
    CONSTRAINT fk_job_skills_job
        FOREIGN KEY (job_id)
        REFERENCES jobs (job_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    -- Deleting a skill that is still in use is BLOCKED. Losing a skill silently
    -- would distort analytics, so the database forces a deliberate decision.
    CONSTRAINT fk_job_skills_skill
        FOREIGN KEY (skill_id)
        REFERENCES skills (skill_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_job_skills_job_id_positive
        CHECK (job_id > 0),

    CONSTRAINT chk_job_skills_skill_id_positive
        CHECK (skill_id > 0)
);


-- =============================================================================
-- 5. INDEXES
--    Every index below exists to support a specific analysis query:
--      - top skills per company / per role
--      - skill demand trends over time
--      - salary and work-mode comparisons
--      - joining from skills to the jobs that require them
-- =============================================================================

-- jobs ---------------------------------------------------------------------

-- Primary time dimension for trend analysis.
CREATE INDEX idx_jobs_posted_date
    ON jobs (posted_date DESC);

-- Supports "how many jobs has company X posted per month / what is its trend".
-- NOTE: this composite index also serves plain company_id lookups (company_id is
-- the leading column), so a separate single-column index on company_id is
-- deliberately NOT created - it would only duplicate work on every INSERT.
CREATE INDEX idx_jobs_company_posted_date
    ON jobs (company_id, posted_date DESC);

-- Supports headcount-of-jobs grouped by work arrangement / employment type.
CREATE INDEX idx_jobs_employment_type
    ON jobs (employment_type);

CREATE INDEX idx_jobs_work_mode
    ON jobs (work_mode);

-- Supports salary comparisons and country-level analytics. The composite index
-- below also serves plain country lookups, so no separate index on country.
CREATE INDEX idx_jobs_country_posted_date
    ON jobs (country, posted_date DESC);

CREATE INDEX idx_jobs_salary_min
    ON jobs (salary_min)
    WHERE salary_min IS NOT NULL;

CREATE INDEX idx_jobs_experience_min
    ON jobs (experience_min)
    WHERE experience_min IS NOT NULL;

-- Supports grouping jobs by normalised role title.
CREATE INDEX idx_jobs_job_title_lower
    ON jobs (lower(btrim(job_title)));

-- companies ----------------------------------------------------------------
CREATE INDEX idx_companies_industry
    ON companies (industry);

-- skills -------------------------------------------------------------------
CREATE INDEX idx_skills_skill_category
    ON skills (skill_category);

-- job_skills ---------------------------------------------------------------
-- CRITICAL: without this index, "which jobs require Python?" would need a full
-- scan of the junction table, because the PK only supports job_id lookups.
CREATE INDEX idx_job_skills_skill_id
    ON job_skills (skill_id);


-- =============================================================================
-- 6. DOCUMENTATION (stored inside the database)
-- =============================================================================

COMMENT ON TABLE  companies IS
    'Dimension table: employers. One company can post many jobs (1:N via jobs.company_id).';

COMMENT ON COLUMN companies.company_id IS
    'Surrogate primary key (identity).';
COMMENT ON COLUMN companies.company_name IS
    'Legal/trading name of the employer. Unique - the same employer is stored once.';
COMMENT ON COLUMN companies.industry IS
    'Industry sector of the employer, e.g. Information Technology, Healthcare, Finance.';
COMMENT ON COLUMN companies.company_size IS
    'Normalised headcount bucket: MICRO_1_10, SMALL_11_50, MEDIUM_51_200, LARGE_201_500, XLARGE_501_1000, ENTERPRISE_1000_PLUS, UNKNOWN. NULL = not disclosed.';
COMMENT ON COLUMN companies.headquarters IS
    'Free-text headquarters city/country. NULL = not available.';

COMMENT ON TABLE  jobs IS
    'Fact table: job postings. One row per posting, posted by exactly one company (1:N from companies).';

COMMENT ON COLUMN jobs.job_id IS
    'Surrogate primary key (identity).';
COMMENT ON COLUMN jobs.company_id IS
    'FK -> companies.company_id. NOT NULL because a posting cannot exist without an employer. ON DELETE CASCADE.';
COMMENT ON COLUMN jobs.job_title IS
    'Title as advertised, e.g. "Data Analyst". Analysed in a normalised (lowercase, trimmed) form.';
COMMENT ON COLUMN jobs.location IS
    'City / office location as advertised. May be "Remote" for remote postings.';
COMMENT ON COLUMN jobs.country IS
    'Country of the posting. Expected format: ISO 3166-1 alpha-2 (e.g. IN, US, GB).';
COMMENT ON COLUMN jobs.employment_type IS
    'Contract type: FULL_TIME, PART_TIME, CONTRACT, INTERNSHIP, TEMPORARY, FREELANCE, OTHER, UNKNOWN.';
COMMENT ON COLUMN jobs.work_mode IS
    'Work arrangement: REMOTE, HYBRID, ONSITE, UNKNOWN. The single most requested field for job-market analytics.';
COMMENT ON COLUMN jobs.experience_min IS
    'Minimum required experience in years. NULL = not specified.';
COMMENT ON COLUMN jobs.experience_max IS
    'Maximum required experience in years. Constrained to be >= experience_min.';
COMMENT ON COLUMN jobs.salary_min IS
    'Lower bound of the advertised pay, as NUMERIC (never floating point). NULL = not disclosed.';
COMMENT ON COLUMN jobs.salary_max IS
    'Upper bound of the advertised pay. Constrained to be >= salary_min.';
COMMENT ON COLUMN jobs.currency IS
    'ISO 4217 3-letter code (INR, USD, EUR). Mandatory whenever a salary figure is present.';
COMMENT ON COLUMN jobs.salary_period IS
    'Basis of the salary figure: YEARLY, MONTHLY, WEEKLY, DAILY, HOURLY. Mandatory whenever a salary figure is present, so mixed pay periods are never compared as if they were equal.';
COMMENT ON COLUMN jobs.posted_date IS
    'Date the posting was published. Primary time dimension for trend analysis.';
COMMENT ON COLUMN jobs.description IS
    'Full posting text. Free text, kept for later full-text search and NLP feature extraction.';

COMMENT ON TABLE  skills IS
    'Dimension table: distinct skills. One skill can be required by many jobs (M:N via job_skills).';

COMMENT ON COLUMN skills.skill_id IS
    'Surrogate primary key (identity).';
COMMENT ON COLUMN skills.skill_name IS
    'Clean, canonical skill name, e.g. "Python". Uniqueness is case-insensitive via uq_skills_skill_name_lower.';
COMMENT ON COLUMN skills.skill_category IS
    'Analytical grouping used for aggregation, e.g. Programming Language, Database, Cloud, Data Science, Soft Skill.';

COMMENT ON TABLE  job_skills IS
    'Junction table resolving the MANY-TO-MANY relationship between jobs and skills. One row = this job requires this skill.';

COMMENT ON COLUMN job_skills.job_id IS
    'FK -> jobs.job_id. Part of the composite primary key. ON DELETE CASCADE.';
COMMENT ON COLUMN job_skills.skill_id IS
    'FK -> skills.skill_id. Part of the composite primary key. ON DELETE RESTRICT: a skill still in use cannot be deleted.';


-- =============================================================================
-- SUMMARY
--   companies  1 --- N  jobs
--   skills     N --- M  jobs      (through job_skills)
-- =============================================================================

COMMIT;
